cam: # cam parameters (general parameters used for all 4 joints)
  d: 55 # (cm) robot link length; required for muscle-cam tangency calculation
  phi_range: [0, 180] # (deg) cam parameterization angle range (range for which cam geometry exists)
  beta_range: [-20, 200] # (deg) joint angle (cam) range for cam profile calculations
  beta_inc: 10 # (deg) joint angle (cam) increment for cam profile calculations

knee: # knee joint parameters
  rad0: 0.045 # (m) cam radius at zero degrees
  slope: 0 # (cm/rad) cam profile radius slope
  theta_range: [180, 0] # (deg) joint angle theta range over which to map cam angle beta from 0 to 180  
  k_tendon: 8200 # (N/m) tendon stiffness (in series with muscle)
  k_anta: 2.1 # (Nm/rad) antagonistic spring stiffness (142.8x24.0 mm nylon strip)
  q_anta_limit: 0 # antagonistic spring engagement angle
  b: 0.03 # (N-m/rad/s) joint damping

hip: # hip joint parameters
  rad0: 0.045
  slope: 0
  theta_range: [-90, 90]
  k_tendon: 8200
  k_anta: 2.5 # 160x25 mm rubber strips at hips
  q_anta_limit: 0.14824150497 # -0.20082449502810373 rad + 20 deg
  b: 0.03

model: # overall robot model parameters
  joint_order: [knee_right, hip_right, hip_left, knee_left] # order of joints
  mu: 0.9 # Coulomb foot friction coefficient (unused)

morphology: # robot morphology [shank_r, thigh_r, torso, thigh_l, shank_l]
  l: [0.55, 0.55, 0.55, 0.55, 0.55] # (m) link lengths
  m: [0.293, 0.472, 0.985, 0.472, 0.293] # (kg) robot link masses: tethered robot
  r_cyl: 0.02 # (m) cylinder radius of each link for inertial calcs
  # J: 1/12*m*(3*r_cyl^2 + l^2); # (kg/m^2) # cylinder inertia formula

state0: # initial robot state
  q0: [0, 161.7, -59.1, -59.1, 161.7] # based on tape-marked-start-pose.MOV
  qd0: [0, 0, 0, 0, 0]  # (rad/s) [angle 1, knee_r, hip_r, hip_l, knee_l] initial joint velocities

control: # control parameters [knee_r, hip_r, hip_l, knee_l]
  p_max: [255, 241, 241, 255] #241 # (gauge kPa) (35 psi) max muscle pressure
  t_musc_activate: [0.0, 0.0, 0.0, 0.0] # (sec) muscle activation timings

pneumatic: # pneumatic system parameters
  gas: air # gas type
  Rs: 287.0550
  T: 296.15
  l_tube_valve_musc: 74 # (in)  ~2.0" valve fittings + 68.75" valve to muscle + ~3.2" muscle inlet tube
  d_tube_valve_musc: 0.1575 # (in) 3/16" ID #NOTE: reduced from nominal 0.1875" dimension
  eps_tube: 1.0e-5 # (m) TODO: how to determine? can vary from 1.5e-6 to 1e-5
  mu_tube: 1.8377e-5
  v_source: 1.475e-3 # (m^3) Ninja SL 90 carbon fiber paintball tank (90 cubic in)
  time_constant_valve: 1.0e-3
  init_mass: 7.873172488131229e-05

cam_params:
  dimension: [1920, 1080] # (pix) camera dimension
  pose: # camera pose in world frame
    point: [2.5019, 0, 0]
    Ry: -1.5708
  # from OpenCV checkerboard cal:
  matrix:
    [[930.61550934,  0.,             957.52437616], 
    [0,              932.40029846,   552.74942762],
    [0,              0,              1           ]] 
  dist: [-0.271825734,  0.0864954022, -0.000255924635,  0.000889888021, -0.0136882404]
